name: BuildAndTest

on:
  push:
    branches: [master, feature]
  pull_request:
    branches: [master, feature]

env:
  app-name: "dnetwebapp"
  rg-name: "devopstest"

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, Windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish myWebApp.csproj -c Release -o website

    
    - name: Upload a Build and Test Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: webApp_artifact
        path: website/**
        if-no-files-found: error
        retention-days: 90


  deploy_staging:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: PRE-PROD
      url: https://dnetwebapp.azurewebsites.net/

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: webApp_artifact
        path: website

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app-name }}
        slot-name: staging
        package: website

    - name: az cli logout
      run: az logout

